### PR TITLE
test: add failing test for ignoreWhitespace

### PR DESCRIPTION
**Pull request by ondrejmirtes**

### CODE REVIEW

**Comment by ondrejmirtes** [comment]
Hi, currently the diff of the strings inside the test looks like this:

```diff
@@ -2,9 +2,5 @@

 function foo(\DateTimeImmutable $date)
 {
-    if ($date) {
-        echo 'foo';
-    } else {
-        echo 'bar';
-    }
+    echo 'foo';
 }
```

But I was hoping for something more like this:

```diff
@@ -2,9 +2,5 @@

 function foo(\DateTimeImmutable $date)
 {
-    if ($date) {
     echo 'foo';
-    } else {
-        echo 'bar';
-    }
 }
```

P. S. Thank you for this library, otherwise it looks and works awesome! :)

**Comment by ondrejmirtes** [comment]
I've wanted to achieve a similar thing that GitHub does, compare these two renderings:

* https://github.com/phpstan/phpstan-src/commit/2335152861184bb0d3fc3562d24b07728c4c2c48
* https://github.com/phpstan/phpstan-src/commit/2335152861184bb0d3fc3562d24b07728c4c2c48?w=1 (ignore whitespaces)

**Comment by jfcherng** [comment]
Thanks for discovering this. I did some tries but can't make it at this moment :cry: 

---

**Update**: It looks like I've gotten some progress, but there is no guarantee that I'll make it done :+1:

**Comment by jfcherng** [comment]
Not exactly the same but LGTM now. `6.7.6` has been released. :fireworks: 

```diff
@@ -2,9 +2,5 @@
 
 function foo(\DateTimeImmutable $date)
 {
-    if ($date) {
         echo 'foo';
-    } else {
-        echo 'bar';
-    }
 }
```

```diff
@@ -125,11 +125,14 @@
     {
         $resolved = [];
 
-        foreach ($phpDocNode->getMethodTagValues() as $tagValue) {
+        foreach (['@method', '@psalm-method', '@phpstan-method'] as $tagName) {
+            foreach ($phpDocNode->getMethodTagValues($tagName) as $tagValue) {
             $parameters = [];
             foreach ($tagValue->parameters as $parameterNode) {
                 $parameterName = substr($parameterNode->parameterName, 1);
-                $type = $parameterNode->type !== null ? $this->typeNodeResolver->resolve($parameterNode->type, $nameScope) : new MixedType();
+                    $type = $parameterNode->type !== null
+                        ? $this->typeNodeResolver->resolve($parameterNode->type, $nameScope)
+                        : new MixedType();
                 if ($parameterNode->defaultValue instanceof ConstExprNullNode) {
                     $type = TypeCombinator::addNull($type);
                 }
@@ -150,10 +153,13 @@
             }
 
             $resolved[$tagValue->methodName] = new MethodTag(
-                $tagValue->returnType !== null ? $this->typeNodeResolver->resolve($tagValue->returnType, $nameScope) : new MixedType(),
+                    $tagValue->returnType !== null
+                        ? $this->typeNodeResolver->resolve($tagValue->returnType, $nameScope)
+                        : new MixedType(),
                 $tagValue->isStatic,
                 $parameters
             );
+            }
         }
 
         return $resolved;
```

**Comment by ondrejmirtes** [comment]
Thank you! It's beautiful now and I appreciate your help :)

**Pull request merged**
