### PR TITLE
test: add failing test

### PR DESCRIPTION
**Pull request by ondrejmirtes**
I like the improvements in 6.7.6 but there's seem to be a regression. The test from the last "Failing test" commit passes on 6.7.5.

What's interesting is that the "Passing test" commit contains the same change but the sample file in "Failing test" is bigger. So it looks like it's some kind of state machine corruption or something like that (I have no idea how a diff engine is written, sorry).

This is `diff -u` output:

```diff
--- tests/data/WorkerCommandA.php	2020-08-22 14:55:44.000000000 +0200
+++ tests/data/WorkerCommandB.php	2020-08-22 14:56:19.000000000 +0200
@@ -215,11 +215,6 @@
 	{
 		echo 'haha';
 		return;
-
-		echo 'blabla';
-		if (false) {
-
-		}
 	}

 }
```

But currently this library generates a diff that looks like this:

```
@@ -215,11 +215,6 @@
 	{
 		echo 'haha';
 		return;
-
-		echo 'blabla';
-		if (false) {
-
-		}
-	}
-
-}
+	}
+
+}
```

I appreciate your help!

### CODE REVIEW

**Comment by jfcherng** [comment]
Thanks. This has been fixed. `6.7.7` has been released.

**Comment by ondrejmirtes** [comment]
Thank you, works like a charm! BTW you should join GitHub Sponsors program, I definitely know about at least one fan :)

**Comment by jfcherng** [comment]
> BTW you should join GitHub Sponsors program,

I did but no luck at this moment :smile: 

image

**Comment by ondrejmirtes** [comment]
@jfcherng You just need to have a bank account in a supported country, I also joined the program even before Czech Republic was supported, because I have the Revolut app (digital bank) where you can generate a bank account in any currency... I'm sure there are many apps like that you can choose from :) Good luck!

**Comment by jfcherng** [comment]
> I have the Revolut app (digital bank) where you can generate a bank account in any currency... I'm sure there are many apps like that you can choose from :) Good luck!

Thanks for this information! I'll investigate when I am available. :heart:

**Pull request merged**
