### PR TITLE
lineNumber option

### PR DESCRIPTION
**Pull request by hasan-ozbey**
Adds lineNumber option for HTML renderers.

I'm building a Flarum extension and line numbers ruins the display in a modal.

### CODE REVIEW

**Comment by jfcherng** [comment]
> ruins the display in a modal

how?

---

I would prefer this being done via CSS from the user-side since I consider this as a rare situation.

For example,
```css
.diff.diff-inline thead th:nth-child(1),
.diff.diff-inline thead th:nth-child(2),
.diff.diff-inline tbody tr[data-type] > th:nth-child(1),
.diff.diff-inline tbody tr[data-type] > th:nth-child(2) {
    display: none;
}
```

Mmm... the side-by-side one seems not able to be done like the above one. But if your issue comes from a narrow modal, I think that side-by-side is the widest layout and will be never working as intended?

**Comment by jfcherng** [comment]
I have fixed phan errors in `v6`, please rebase or merge. There are still PSR-12 issues but they can be fixed by `$ composer fix` easily.

**Comment by hasan-ozbey** [comment]
wider modal is not a solution because there are mostly small changes in a forum environment also line numbers in a table is not good for a responsive design. I'd prefer a CSS option for this too, maybe we can add new class names for `<th>` nodes which shows up with Line Numbers?

**Comment by jfcherng** [comment]
But I think pure CSS solution cannot cover the `colspan` problem in the `SideBySide` renderer.

https://github.com/jfcherng/php-diff/blob/1140ec220a25a667df011b5e072b9510bb1d3c55/src/Renderer/Html/SideBySide.php#L58-L64

Another solution without add an extra option is creating something like `InlineNoLineNumber` renderer.

**Comment by hasan-ozbey** [comment]
Another solution could be removing `colspan` attributes from the PHP and define them within the CSS using new class names of `<th>` nodes. I think a new renderer is a bit too much for this.

**Comment by jfcherng** [comment]
> Another solution could be removing colspan attributes from the PHP and define them within the CSS using new class names of <th> nodes

Afaik, there is no `colspan` equivalent in CSS?

**Comment by hasan-ozbey** [comment]
Whoops! You're right, i completely forgot it. Let's think about a CSS solution little more --

**Comment by jfcherng** [comment]
Thanks. Added in `6.4.0`.

**Comment by jfcherng** [comment]
Changing HTML renderers' output to 

- Be responsive
- Use CSS for show/hide line numbers (or other features)

could be BC break I guess.

People may discuss and implement in `v7` if that ever happens.

**Pull request merged**
